### ISSUE TITLE
Is it possible to display the font name based on the operating system language or the specified language?

### ISSUE THREAD

**Issue by OneSeven** [adrg/sysfont#19]
For example: Microsoft YaHei Microsoft YaHei C:\Windows\Fonts\msyh.ttc corresponds to Chinese: "微软雅黑"
Please， thanks !

**Comment by adrg** [comment]
Hi @OneSeven. Thank you for your interest in the library. This is not supported right now, but I do plan on implementing it in the future, although I cannot really make estimations on when that will be. It heavily depends on my free time.

This is also discussed in issue https://github.com/adrg/sysfont/issues/4. Maybe we should close this issue and continue the conversation there.

**Comment by OneSeven** [comment]
> Hi @OneSeven. Thank you for your interest in the library. This is not supported right now, but I do plan on implementing it in the future, although I cannot really make estimations on when that will be. It heavily depends on my free time.
> 
> This is also discussed in issue #4. Maybe we should close this issue and continue the conversation there.

OK.
